name: "Parallel Bash Commands"
description: "Executes a list of bash commands in parallel and waits for them all to successfully complete"

runs:
  using: "composite"
  steps:
    - id: setParallelCommands
      run: |
        COMMANDS=$(node -e "console.log(JSON.stringify(['${{ inputs.cmd1 }}', '${{ inputs.cmd2 }}', '${{ inputs.cmd3 }}', '${{ inputs.cmd4 }}', '${{ inputs.cmd5 }}', '${{ inputs.cmd6 }}', '${{ inputs.cmd7 }}', '${{ inputs.cmd8 }}', '${{ inputs.cmd9 }}', '${{ inputs.cmd10 }}'].filter(Boolean)))")
        echo "::set-output name=commands::$COMMANDS"
      shell: bash
    - run: ${{ github.action_path }}/run.sh '${{ steps.setParallelCommands.outputs.commands }}'
      shell: bash

# Github actions are currently only able to accept strings as inputs to we have explicitly handle a certain number of
# inputs that the user might reasonably expect to run in parallel. For now, we explicitly handle 10 commands as inputs.
inputs:
  cmd1:
    description: "Bash command"
    required: true # We should really have at least one command for the action to even do anything at all...
  cmd2:
    description: "Bash command"
    required: false
  cmd3:
    description: "Bash command"
    required: false
  cmd4:
    description: "Bash command"
    required: false
  cmd5:
    description: "Bash command"
    required: false
  cmd6:
    description: "Bash command"
    required: false
  cmd7:
    description: "Bash command"
    required: false
  cmd8:
    description: "Bash command"
    required: false
  cmd9:
    description: "Bash command"
    required: false
  cmd10:
    description: "Bash command"
    required: false